"use client";

import { TierInfoCard } from "@/components/ui/TierBadge";
import { CertifiedBadge } from "@/components/ui/CertifiedBadge";
import { ExtremeDangerBadge } from "@/components/ui/ExtremeDangerBadge";
import { Shield, Sparkles, AlertTriangle, FileSearch, BrainCircuit, AlertOctagon } from "lucide-react";
import Link from "next/link";

export default function AboutPage() {
    return (
        <div className="min-h-screen py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
            <div className="space-y-12">
                {/* Header */}
                <div className="text-center space-y-4">
                    <h1 className="text-4xl font-bold text-white tracking-tight sm:text-5xl">
                        About <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">SkillGuard</span>
                    </h1>
                    <p className="text-lg text-slate-400 max-w-2xl mx-auto">
                        An AI-powered security audit platform for autonomous agents and skills.
                    </p>
                </div>

                {/* Disclaimer Box */}
                <div className="bg-amber-950/30 border border-amber-900/50 rounded-xl p-6 flex gap-4">
                    <AlertTriangle className="w-6 h-6 text-amber-500 flex-shrink-0 mt-1" />
                    <div className="space-y-2">
                        <h3 className="text-lg font-semibold text-amber-400">Important Disclaimer</h3>
                        <p className="text-slate-300 text-sm leading-relaxed">
                            SkillGuard is an independent project and is **not associated with Google**.
                            We utilize Google's Gemini 3 Pro and Flash models for deep code analysis,
                            but the badges and certifications are generated by our own algorithms.
                        </p>
                        <p className="text-slate-400 text-sm leading-relaxed">
                            AI models can make mistakes. A "Platinum" or "Obsidian" score does not guarantee
                            100% security. Always review code manually before deploying critical agents.
                        </p>
                    </div>
                </div>

                {/* How it Works */}
                <div className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                        <FileSearch className="w-6 h-6 text-indigo-400" />
                        How It Works
                    </h2>
                    <div className="grid md:grid-cols-2 gap-6">
                        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6 space-y-4">
                            <div className="w-10 h-10 bg-blue-500/10 rounded-lg flex items-center justify-center text-blue-400">
                                <FileSearch className="w-5 h-5" />
                            </div>
                            <h3 className="font-semibold text-white">1. Static Analysis</h3>
                            <p className="text-sm text-slate-400">
                                We scan the repository for sensitive files (API keys, .env),
                                dangerous capabilities (shell access, network), and
                                insecure coding patterns using regex and AST parsing.
                            </p>
                        </div>
                        <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6 space-y-4">
                            <div className="w-10 h-10 bg-purple-500/10 rounded-lg flex items-center justify-center text-purple-400">
                                <BrainCircuit className="w-5 h-5" />
                            </div>
                            <h3 className="font-semibold text-white">2. Deep Audit (Gemini)</h3>
                            <p className="text-sm text-slate-400">
                                We select the most critical files and feed them to **Gemini 3 Pro**,
                                asking it to identify logic flaws, prompt injection risks,
                                and supply chain vulnerabilities that static tools miss.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Badge System */}
                <div className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                        <Shield className="w-6 h-6 text-indigo-400" />
                        The Badge System
                    </h2>
                    <p className="text-slate-400">
                        Agents are assigned a tier based on their Safety Score, which combines
                        static analysis results and AI-detected vulnerabilities.
                    </p>

                    <TierInfoCard />
                </div>

                {/* Gemini Certified */}
                <div className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                        <Sparkles className="w-6 h-6 text-indigo-400" />
                        Gemini Certified Safe
                    </h2>
                    <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-8 flex flex-col md:flex-row items-center gap-8">
                        <div className="transform scale-125">
                            <CertifiedBadge />
                        </div>
                        <div className="space-y-4">
                            <p className="text-slate-300 leading-relaxed">
                                The <strong>Gemini Certified Safe</strong> badge is awarded only to agents
                                that achieve **Platinum, Diamond, or Obsidian** status.
                            </p>
                            <p className="text-slate-400 text-sm">
                                This indicates that both our static analysis and the Gemini 3 Pro model
                                found <strong>zero critical or high-risk vulnerabilities</strong>, and the
                                agent follows security best practices.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Extreme Danger Warning */}
                <div className="space-y-6">
                    <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                        <AlertOctagon className="w-6 h-6 text-red-500" />
                        Extreme Danger
                    </h2>
                    <div className="bg-red-950/20 border border-red-900/50 rounded-xl p-8 flex flex-col md:flex-row items-center gap-8">
                        <div>
                            <ExtremeDangerBadge evidence={[
                                "Attempts to bypass previous instructions",
                                "Attempts to suppress reporting",
                                "Suspicious safety marker: SAFE_CODE_MARKER"
                            ]} />
                        </div>
                        <div className="space-y-4">
                            <p className="text-slate-300 leading-relaxed">
                                The <strong>Extreme Danger</strong> badge triggers when our system detects
                                <strong> active attempts to bypass security analysis</strong> or alter the underlying intentions of the agent.
                            </p>
                            <p className="text-red-400 text-sm font-medium">
                                Agents with this badge should be treated with extreme caution.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Footer Action */}
                <div className="pt-12 text-center">
                    <Link href="/scan">
                        <button className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-colors">
                            Scan an Agent Now
                        </button>
                    </Link>
                </div>
            </div>
        </div>
    );
}

